/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:c6a7145d-3c6d-45e5-ac66-d5d6606b12d0",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_xeya0XSmr",
    "aws_user_pools_web_client_id": "276u489dcle0dtcb952ridhtse",
    "oauth": {
        "domain": "thehomiecompany5b32379e-5b32379e-dev.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "htpp://localhost:3000/",
        "responseType": "token"
    },
    "federationTarget": "COGNITO_USER_AND_IDENTITY_POOLS",
    "aws_appsync_graphqlEndpoint": "https://uzadsus2kfd3fmdx6ldnahk77m.appsync-api.ap-south-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-south-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "billgenerator",
            "endpoint": "https://nc7z2zjckf.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "addbill",
            "endpoint": "https://0h07h1nhv3.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "razorpaygenerator",
            "endpoint": "https://zfhuhnotsc.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "couponvalidator",
            "endpoint": "https://dch4jq56sh.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        },
        {
            "name": "codorder",
            "endpoint": "https://bga3rm4qb8.execute-api.ap-south-1.amazonaws.com/dev",
            "region": "ap-south-1"
        }
    ],
    "aws_user_files_s3_bucket": "thehomiecompany7fc69ecced674785b1b12e58937f742e194204-dev",
    "aws_user_files_s3_bucket_region": "ap-south-1"
};


export default awsmobile;